### ISSUE TITLE
[HOI-0145] Project validation through Shape Expression

### ISSUE THREAD

**Issue by thewillyhuman** [weso/hercules-ontology#145]
I open this issue to discuss the structure of the shape used to validate the project class of ontology.

**Class:**
https://github.com/weso/hercules-ontology/blob/86659a7b83b6754492885771b3fa730738af7ede/src/asio-core.ttl#L1437-L1439

**Comment by alejgh** [comment]
These some are of the elements that compose at project. Cardinalities, if given, are tentative and should be discussed. I'm used to shapes from Wikidata where almost all fields are optional since data is extracted from multiple heterogeneous sources, but we need to define what information __must__ exist for something to be a project:
* asio:projectEndDate xsd:date ?
* asio:projectStartDate xsd:date
* asio:projectObjective xsd:string ?
* rdf:type [asio:RegionalProject asio:NationalProject asio:EuropeanProject asio:InternationalProject]
* asio:isFundedBy @asio:FundingProgramme *
* asio:hasResearchField @asio:ESSubjectAreas3rdList OR @asio:ESSubjectAreas2ndList OR @asio:ESSubjectAreas1ndList *
* asio:projectOutcome . * (maybe we should restrict this more, in theory the outcome should be a patent, publication, product...)
* asio:projectAcronym xsd:string ?
* asio:projectId xsd:integer + (we have to think about the cardinality. will all projects have an ID? I think a project can have multiple IDs: e.g. one from CORDIS, other from the research institute participating on the project...)
* asio:projectKeyword xsd:string *
* asio:coordinatedBy @foaf:Agent +
* rdfs:label xsd:string
* rdfs:comment xsd:string ?

There is still work to do on the following fields:
* asio:projectStatus: There is a discussion whether this should be a string or a 'enum' with a fixed set of values.
* I think we also need a field to link other participants of the project besides the coordinator.
* A field to link the project with its budget.

**Comment by thewillyhuman** [comment]
**What about this?**
```sparql
prefix asio: <http://purl.org/hercules/asio/core#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Asio project node.
asio:ProjectShape EXTRA rdf:type {

  # Project type.
  rdf:type [asio:RegionalProject asio:NationalProject asio:EuropeanProject asio:InternationalProject]+ ;

  # Label and comment.
  rdfs:label rdf:langString + ;
  rdfs:comment rdf:langString * ;

  # Project ID.
  asio:projectId xsd:integer ? ;

  # Project acronym.
  asio:projectAcronym xsd:string ? ;

  # Project coordinator/s.
  asio:coordinatedBy @asio:AgentShape * ;

  # Project aim.
  asio:projectObjective rdf:langString ? ;

  # Project keywords.
  asio:projectKeyword rdf:langString * ;

  # Project dates.
  asio:projectEndDate xsd:date ? ;
  asio:projectStartDate xsd:date ;

  # Project foundings.
  asio:isFundedBy @asio:FundingProgrammeShape * ;

  # Project research field.
  asio:hasResearchField @asio:ResearchFieldShape * ;

  # Project outcome.
  asio:projectOutcome . * ;
}

asio:AgentShape {
  a [ foaf:Agent ] 
}

asio:FundingProgrammeShape {
}

asio:ResearchFieldShape @asio:ESSubjectAreas3rdListShape OR @asio:ESSubjectAreas2ndListShape OR @asio:ESSubjectAreas1ndListShape

asio:ESSubjectAreas3rdListShape { }
asio:ESSubjectAreas2ndListShape { }
asio:ESSubjectAreas1ndListShape { }
```

**Comment by alejgh** [comment]
Ok, we are losing some information there since the subject areas schemes (e.g. ESSubjectAreas3rdList) come from asioModules and not from asio (core), but I think that is not important for the validation. Or is it? Maybe we should also update the value of the asio prefix, currently it is in the ontology:
```turtle
@prefix asio: <http://purl.org/hercules/asio/core#> .
```

**Comment by thewillyhuman** [comment]
Prefix updated
