### ISSUE TITLE
CQ020 - Point out tendencies in lines of research based on available data. 

### ISSUE THREAD

**Issue by sofimrtn** [weso/hercules-ontology#25]
Original source:

> Como usuario necesito detectar tendencias en áreas y líneas investigación a partir de los datos disponibles en Hércules.

Translated:

> As a user I would need to perceive tendencies in areas and lines of research based on the available data in Hercules.

**Comment by alejgh** [comment]
@spitxa what is the domain of the 'hasScientificDomain' property? 

If we can say a _ScientificPublication hasScientificDomain ''domain''_, we can obtain the number of publications for each scientific domain for the last X months/years to see tendencies. Do you think this would be a good solution for this competence question?

Maybe we can show the tendencies based on another criteria, this is a very open question.

**Comment by spitxa** [comment]
the _hasScientificDomain_ property has as a clear range _skos:Concept_ (i haven't added it so far because that ad-hoc vertical module was still pendint but i've just added it to the core) but i haven't set a domain because it can be several. for instance, the one you suggested (_ScientificPublication_), but also _Project_, _AcademicDegree_, _ResearchContribution_, _ResearchField_, _ResearchMethod_, _ResearchObject_, _ResearchProblem_, _ResearchResult_, etc. that's why i left it open for the moment.
anyway, your point is good and we should make a decision. let me think about it.

**Comment by spitxa** [comment]
i've filtered & pruned domain candidates for the _hasScientificDomain_ property.
-removed: _ResearchContribution_, _ResearchField_, _ResearchMethod_, _ResearchObject_, _ResearchProblem_, _ResearchResult_ (these classes originally belong to the ORKG ontology)
-dubious: _AcademicDegree_
-final candidates (so far): _ScientificPublication_, _Project_, _Patent_ (newly added)
